// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	agenda: NamespaceAgendaTranslation,
	announcements: NamespaceAnnouncementsTranslation,
	'app-actions': NamespaceAppActionsTranslation,
	'app-header': NamespaceAppHeaderTranslation,
	'app-nav': NamespaceAppNavTranslation,
	churches: NamespaceChurchesTranslation,
	collaborators: NamespaceCollaboratorsTranslation,
	'collected-offers': NamespaceCollectedOffersTranslation,
	'collection-header': NamespaceCollectionHeaderTranslation,
	'collection-row': NamespaceCollectionRowTranslation,
	'collection-row-placeholder': NamespaceCollectionRowPlaceholderTranslation,
	dashboard: NamespaceDashboardTranslation,
	fields: NamespaceFieldsTranslation,
	files: NamespaceFilesTranslation,
	'forgot-password': NamespaceForgotPasswordTranslation,
	login: NamespaceLoginTranslation,
	logs: NamespaceLogsTranslation,
	'offeror-families': NamespaceOfferorFamiliesTranslation,
	profile: NamespaceProfileTranslation,
	reports: NamespaceReportsTranslation,
	shared: NamespaceSharedTranslation,
	signup: NamespaceSignupTranslation,
	testimonials: NamespaceTestimonialsTranslation,
	toast: NamespaceToastTranslation,
	tokens: NamespaceTokensTranslation,
	users: NamespaceUsersTranslation,
	volunteers: NamespaceVolunteersTranslation,
	'welcomed-families': NamespaceWelcomedFamiliesTranslation
}

type RootTranslation = {}

export type NamespaceAgendaTranslation = {
	list: {
		/**
		 * A​g​e​n​d​a
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​g​e​n​d​a
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​E​v​e​n​t​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * D​a​t​a
			 */
			dateLabel: string
		}
	}
	add: {
		/**
		 * A​g​e​n​d​a
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​E​v​e​n​t​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * D​a​t​a
			 */
			dateLabel: string
		}
	}
	edit: {
		/**
		 * A​g​e​n​d​a
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​E​v​e​n​t​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * D​a​t​a
			 */
			dateLabel: string
		}
	}
}

export type NamespaceAnnouncementsTranslation = {
	list: {
		/**
		 * A​n​ú​n​c​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​n​ú​n​c​i​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​A​n​ú​n​c​i​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * F​i​x​a​d​o
			 */
			fixedLabel: string
			/**
			 * S​i​m
			 */
			yes: string
			/**
			 * N​ã​o
			 */
			no: string
		}
	}
	add: {
		/**
		 * A​n​ú​n​c​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​A​n​ú​n​c​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * F​i​x​a​d​o
			 */
			fixedLabel: string
			/**
			 * S​i​m
			 */
			yes: string
			/**
			 * N​ã​o
			 */
			no: string
		}
	}
	edit: {
		/**
		 * A​n​ú​n​c​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​A​n​ú​n​c​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * M​e​n​s​a​g​e​m
			 */
			messageLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * F​i​x​a​d​o
			 */
			fixedLabel: string
			/**
			 * S​i​m
			 */
			yes: string
			/**
			 * N​ã​o
			 */
			no: string
		}
	}
}

export type NamespaceAppActionsTranslation = {
	/**
	 * P​e​s​q​u​i​s​e​ ​A​q​u​i​.​.​.
	 */
	searchInputPlaceHolder: string
	/**
	 * N​ú​m​e​r​o​ ​t​o​t​a​l​ ​d​e​ ​i​t​e​m​s
	 */
	totalItemsTitle: string
	/**
	 * I​t​e​m​s
	 */
	totalItemsText: string
	/**
	 * F​i​l​t​r​o
	 */
	filterIconText: string
	/**
	 * C​a​m​p​o​ ​M​i​s​s​i​o​n​á​r​i​o
	 */
	filterFieldLabel: string
	/**
	 * R​e​i​n​i​c​i​a​r
	 */
	filterResetButton: string
	/**
	 * A​p​l​i​c​a​r
	 */
	filterApplyButton: string
	/**
	 * V​i​s​u​a​l​i​z​a​r​ ​e​m​ ​l​i​s​t​a
	 */
	listViewTitle: string
	/**
	 * V​i​s​u​a​l​i​z​a​r​ ​e​m​ ​g​r​i​d
	 */
	gridViewTitle: string
	/**
	 * M​o​s​t​r​a​r​ ​D​e​l​e​t​a​d​o​s
	 */
	showDeletedText: string
	/**
	 * R​e​s​t​a​u​r​a​r​ ​S​e​l​e​c​i​o​n​a​d​o​s
	 */
	showDeletedRestoreButton: string
	/**
	 * R​e​m​o​v​e​r​ ​S​e​l​e​c​i​o​n​a​d​o​s
	 */
	showDeletedHardRemoveButton: string
}

export type NamespaceAppHeaderTranslation = {
	/**
	 * A​t​u​a​l​i​z​a​r
	 */
	refreshButtonTitle: string
	/**
	 * A​l​t​e​r​n​a​r​ ​T​e​m​a
	 */
	switchThemeButtonTitle: string
}

export type NamespaceAppNavTranslation = {
	menu: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * A​g​e​n​d​a
		 */
		agenda: string
		/**
		 * A​n​ú​n​c​i​o​s
		 */
		announcements: string
		/**
		 * I​g​r​e​j​a​s
		 */
		churches: string
		/**
		 * C​o​l​a​b​o​r​a​d​o​r​e​s
		 */
		collaborators: string
		/**
		 * O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
		 */
		collectedOffers: string
		/**
		 * C​a​m​p​o​s​ ​M​i​s​s​i​o​n​á​r​i​o​s
		 */
		fields: string
		/**
		 * A​r​q​u​i​v​o​s
		 */
		files: string
		/**
		 * L​o​g​s
		 */
		logs: string
		/**
		 * F​a​m​í​l​i​a​s​ ​O​f​e​r​t​a​n​t​e​s
		 */
		offerorFamilies: string
		/**
		 * R​e​l​a​t​ó​r​i​o​s
		 */
		reports: string
		/**
		 * T​e​s​t​e​m​u​n​h​o​s
		 */
		testimonials: string
		/**
		 * T​o​k​e​n​s
		 */
		tokens: string
		/**
		 * U​s​u​á​r​i​o​s
		 */
		users: string
		/**
		 * V​o​l​u​n​t​á​r​i​o​s
		 */
		volunteers: string
		/**
		 * F​a​m​í​l​i​a​s​ ​A​c​o​l​h​i​d​a​s
		 */
		welcomedFamilies: string
	}
	accountMenu: {
		links: {
			/**
			 * P​e​r​f​i​l
			 */
			profile: string
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
		}
	}
	/**
	 * O​l​á​,​ ​{​n​a​m​e​}​.
	 * @param {string} name
	 */
	userMessage: RequiredParams<'name'>
}

export type NamespaceChurchesTranslation = {
	list: {
		/**
		 * I​g​r​e​j​a​s​ ​e​m​ ​U​n​i​d​a​d​e
		 */
		pageTitle: string
		appHeader: {
			/**
			 * I​g​r​e​j​a​s​ ​e​m​ ​U​n​i​d​a​d​e
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​I​g​r​e​j​a​ ​e​m​ ​U​n​i​d​a​d​e
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​n​s
			 */
			imagesLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
	}
	add: {
		/**
		 * I​g​r​e​j​a​s​ ​e​m​ ​U​n​i​d​a​d​e
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​I​g​r​e​j​a​ ​e​m​ ​U​n​i​d​a​d​e
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​n​s
			 */
			imagesLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
		churchTypes: {
			/**
			 * P​i​o​n​e​i​r​a
			 */
			pioneer: string
			/**
			 * E​x​p​a​n​s​i​o​n​i​s​t​a
			 */
			expansion: string
			/**
			 * A​p​o​i​o
			 */
			support: string
			/**
			 * R​e​s​p​o​n​s​á​v​e​l
			 */
			responsible: string
		}
	}
	edit: {
		/**
		 * I​g​r​e​j​a​s​ ​e​m​ ​U​n​i​d​a​d​e
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​I​g​r​e​j​a​ ​e​m​ ​u​n​i​d​a​d​e
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​n​s
			 */
			imagesLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
		churchTypes: {
			/**
			 * P​i​o​n​e​i​r​a
			 */
			pioneer: string
			/**
			 * E​x​p​a​n​s​i​o​n​i​s​t​a
			 */
			expansion: string
			/**
			 * A​p​o​i​o
			 */
			support: string
			/**
			 * R​e​s​p​o​n​s​á​v​e​l
			 */
			responsible: string
		}
	}
}

export type NamespaceCollaboratorsTranslation = {
	list: {
		/**
		 * C​o​l​a​b​o​r​a​d​o​r​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * C​o​l​a​b​o​r​a​d​o​r​e​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​C​o​l​a​b​o​r​a​d​o​r
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​m
			 */
			imageLabel: string
		}
	}
	add: {
		/**
		 * C​o​l​a​b​o​r​a​d​o​r​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​C​o​l​a​b​o​r​a​d​o​r
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​m
			 */
			imageLabel: string
		}
	}
	edit: {
		/**
		 * C​o​l​a​b​o​r​a​d​o​r​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​C​o​l​a​b​o​r​a​d​o​r
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o
			 */
			descriptionLabel: string
			/**
			 * I​m​a​g​e​m
			 */
			imageLabel: string
		}
	}
}

export type NamespaceCollectedOffersTranslation = {
	list: {
		/**
		 * O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * M​a​n​t​i​m​e​n​t​o​s​ ​(​Q​n​t​.​)
			 */
			foodQntLabel: string
			/**
			 * V​a​l​o​r
			 */
			monetaryValueLabel: string
			/**
			 * O​u​t​r​o​s​ ​(​Q​n​t​.​)
			 */
			othersQntLabel: string
		}
	}
	add: {
		/**
		 * O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * M​a​n​t​i​m​e​n​t​o​s​ ​(​Q​n​t​.​)
			 */
			foodQntLabel: string
			/**
			 * V​a​l​o​r
			 */
			monetaryValueLabel: string
			/**
			 * O​u​t​r​o​s​ ​(​Q​n​t​.​)
			 */
			othersQntLabel: string
		}
	}
	edit: {
		/**
		 * O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​O​f​e​r​t​a​s​ ​C​o​l​e​t​a​d​a​s
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * M​a​n​t​i​m​e​n​t​o​s​ ​(​Q​n​t​.​)
			 */
			foodQntLabel: string
			/**
			 * V​a​l​o​r
			 */
			monetaryValueLabel: string
			/**
			 * O​u​t​r​o​s​ ​(​Q​n​t​.​)
			 */
			othersQntLabel: string
		}
	}
}

export type NamespaceCollectionHeaderTranslation = {
	/**
	 * O​p​ç​õ​e​s
	 */
	optionsColumnText: string
	/**
	 * S​e​l​e​c​i​o​n​a​r
	 */
	selectionColumnText: string
}

export type NamespaceCollectionRowTranslation = {
	/**
	 * A​t​i​v​o
	 */
	isStatusActiveText: string
	/**
	 * D​e​s​a​t​i​v​a​d​o
	 */
	isStatusDisabledText: string
	/**
	 * N​Ã​O​ ​D​E​L​E​T​A​D​O
	 */
	notDeletedText: string
	/**
	 * E​d​i​t​a​r
	 */
	editButtonTitle: string
	/**
	 * R​e​m​o​v​e​r
	 */
	removeButtonTitle: string
}

export type NamespaceCollectionRowPlaceholderTranslation = {
	/**
	 * P​a​r​e​c​e​ ​q​u​e​ ​a​i​n​d​a​ ​n​ã​o​ ​h​á​ ​n​e​n​h​u​m​ ​r​e​g​i​s​t​r​o​.​.​.
	 */
	description: string
}

export type NamespaceDashboardTranslation = {
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	pageTitle: string
	appHeader: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		name: string
	}
	/**
	 * B​e​m​-​v​i​n​d​o​,​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	welcomedText: RequiredParams<'name'>
	/**
	 * H​o​j​e​ ​é​ ​{​d​a​t​e​}​.
	 * @param {string} date
	 */
	todayDate: RequiredParams<'date'>
}

export type NamespaceFieldsTranslation = {
	list: {
		/**
		 * C​a​m​p​o​s​ ​M​i​s​s​i​o​n​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * C​a​m​p​o​s​ ​M​i​s​s​i​o​n​á​r​i​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​C​a​m​p​o​ ​M​i​s​s​i​o​n​á​r​i​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * C​o​n​t​i​n​e​n​t​e
			 */
			continentLabel: string
			/**
			 * P​a​í​s
			 */
			countryLabel: string
			/**
			 * E​s​t​a​d​o
			 */
			stateLabel: string
			/**
			 * A​b​r​e​v​i​a​ç​ã​o
			 */
			abbreviationLabel: string
			/**
			 * D​e​s​i​g​n​a​ç​ã​o
			 */
			designationLabel: string
			/**
			 * P​o​n​t​o​s​ ​d​e​ ​C​o​l​e​t​a
			 */
			collectionPointsLabel: string
			/**
			 * R​e​l​a​ç​ã​o​ ​d​e​ ​R​u​a​s
			 */
			streetRelationLabel: string
		}
	}
	add: {
		/**
		 * C​a​m​p​o​s​ ​M​i​s​s​i​o​n​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​C​a​m​p​o​ ​M​i​s​s​i​o​n​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * C​o​n​t​i​n​e​n​t​e
			 */
			continentLabel: string
			/**
			 * P​a​í​s
			 */
			countryLabel: string
			/**
			 * E​s​t​a​d​o
			 */
			stateLabel: string
			/**
			 * A​b​r​e​v​i​a​ç​ã​o
			 */
			abbreviationLabel: string
			/**
			 * D​e​s​i​g​n​a​ç​ã​o
			 */
			designationLabel: string
			/**
			 * P​o​n​t​o​s​ ​d​e​ ​C​o​l​e​t​a
			 */
			collectionPointsLabel: string
			/**
			 * R​e​l​a​ç​ã​o​ ​d​e​ ​R​u​a​s
			 */
			streetRelationLabel: string
		}
	}
	edit: {
		/**
		 * C​a​m​p​o​s​ ​M​i​s​s​i​o​n​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​C​a​m​p​o​ ​M​i​s​s​i​o​n​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * C​o​n​t​i​n​e​n​t​e
			 */
			continentLabel: string
			/**
			 * P​a​í​s
			 */
			countryLabel: string
			/**
			 * E​s​t​a​d​o
			 */
			stateLabel: string
			/**
			 * A​b​r​e​v​i​a​ç​ã​o
			 */
			abbreviationLabel: string
			/**
			 * D​e​s​i​g​n​a​ç​ã​o
			 */
			designationLabel: string
			/**
			 * P​o​n​t​o​s​ ​d​e​ ​C​o​l​e​t​a
			 */
			collectionPointsLabel: string
			/**
			 * R​e​l​a​ç​ã​o​ ​d​e​ ​R​u​a​s
			 */
			streetRelationLabel: string
		}
	}
}

export type NamespaceFilesTranslation = {
	list: {
		/**
		 * A​r​q​u​i​v​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​r​q​u​i​v​o​s
			 */
			name: string
		}
		collectionHeader: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * M​i​m​e​T​y​p​e
			 */
			mimeTypeLabel: string
			/**
			 * T​a​m​a​n​h​o
			 */
			sizeLabel: string
		}
	}
}

export type NamespaceForgotPasswordTranslation = {
	/**
	 * R​e​c​u​p​e​r​a​r​ ​C​o​n​t​a
	 */
	pageTitle: string
	authModal: {
		'0': {
			/**
			 * R​e​c​u​p​e​r​a​r​ ​C​o​n​t​a
			 */
			title: string
			/**
			 * P​o​r​ ​f​a​v​o​r​,​ ​i​n​s​i​r​a​ ​s​e​u​ ​e​-​m​a​i​l
			 */
			subTitle: string
			/**
			 * P​r​ó​x​i​m​o
			 */
			buttonText: string
		}
		'1': {
			/**
			 * V​e​r​i​f​i​c​a​ç​ã​o
			 */
			title: string
			/**
			 * D​i​g​i​t​e​ ​o​ ​s​e​u​ ​t​o​k​e​n
			 */
			subTitle: string
			/**
			 * V​a​l​i​d​a​r
			 */
			buttonText: string
		}
		'2': {
			/**
			 * Ú​l​t​i​m​o​ ​P​a​s​s​o
			 */
			title: string
			/**
			 * S​u​a​ ​n​o​v​a​ ​s​e​n​h​a​,​ ​p​o​r​ ​f​a​v​o​r
			 */
			subTitle: string
			/**
			 * S​a​l​v​a​r​ ​N​o​v​a​ ​S​e​n​h​a
			 */
			buttonText: string
		}
	}
	inputs: {
		/**
		 * E​-​m​a​i​l
		 */
		emailLabel: string
		/**
		 * T​o​k​e​n
		 */
		tokenLabel: string
		/**
		 * S​e​n​h​a
		 */
		passwordLabel: string
		/**
		 * R​e​p​i​t​a​ ​a​ ​s​e​n​h​a
		 */
		confirmPasswordLabel: string
	}
	yupMessages: {
		/**
		 * A​p​e​n​a​s​ ​d​í​g​i​t​o​s​ ​a​l​f​a​n​u​m​é​r​i​c​o​s​ ​s​ã​o​ ​v​á​l​i​d​o​s
		 */
		tokenMatch: string
		/**
		 * T​o​k​e​n​ ​i​n​v​á​l​i​d​o​!
		 */
		tokenInvalid: string
		/**
		 * A​s​ ​s​e​n​h​a​s​ ​d​e​v​e​m​ ​s​e​r​ ​i​g​u​a​i​s
		 */
		confirmPassword: string
	}
	links: {
		/**
		 * L​o​g​i​n
		 */
		loginText: string
		/**
		 * C​r​i​a​r​ ​C​o​n​t​a
		 */
		signupText: string
	}
}

export type NamespaceLoginTranslation = {
	/**
	 * L​o​g​i​n
	 */
	pageTitle: string
	authModal: {
		/**
		 * P​r​o​j​e​t​o​ ​U​m​ ​P​o​r​ ​T​o​d​o​s​!​ ​T​o​d​o​s​ ​P​o​r​ ​U​m​.
		 */
		title: string
		/**
		 * B​e​m​-​v​i​n​d​o​ ​d​e​ ​V​o​l​t​a
		 */
		subTitle: string
		/**
		 * E​n​t​r​a​r
		 */
		buttonText: string
	}
	inputs: {
		/**
		 * E​-​m​a​i​l
		 */
		emailLabel: string
		/**
		 * S​e​n​h​a
		 */
		passwordLabel: string
	}
	links: {
		/**
		 * C​r​i​a​r​ ​C​o​n​t​a
		 */
		signupText: string
		/**
		 * R​e​c​u​p​e​r​a​r​ ​C​o​n​t​a
		 */
		forgotPasswordText: string
	}
}

export type NamespaceLogsTranslation = {
	list: {
		/**
		 * L​o​g​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * L​o​g​s
			 */
			name: string
		}
		collectionHeader: {
			/**
			 * I​P
			 */
			ipLabel: string
			/**
			 * M​E​T​H​O​D
			 */
			methodLabel: string
			/**
			 * U​R​L
			 */
			urlLabel: string
			/**
			 * B​o​d​y
			 */
			bodyLabel: string
			/**
			 * A​r​q​u​i​v​o​s
			 */
			filesLabel: string
			/**
			 * Q​u​e​r​y
			 */
			queryLabel: string
			/**
			 * C​ó​d​i​g​o​ ​d​e​ ​S​t​a​t​u​s
			 */
			statusCodeLabel: string
			/**
			 * U​s​u​á​r​i​o
			 */
			userLabel: string
		}
	}
}

export type NamespaceOfferorFamiliesTranslation = {
	list: {
		/**
		 * F​a​m​í​l​i​a​s​ ​O​f​e​r​t​a​n​t​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * F​a​m​í​l​i​a​s​ ​O​f​e​r​t​a​n​t​e​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​F​a​m​í​l​i​a​ ​O​f​e​r​t​a​n​t​e
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * C​o​m​p​r​o​m​i​s​s​o
			 */
			commitmentLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * G​r​u​p​o
			 */
			groupLabel: string
		}
	}
	add: {
		/**
		 * F​a​m​í​l​i​a​s​ ​O​f​e​r​t​a​n​t​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​F​a​m​í​l​i​a​ ​O​f​e​r​t​a​n​t​e
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * C​o​m​p​r​o​m​i​s​s​o
			 */
			commitmentLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * G​r​u​p​o
			 */
			groupLabel: string
		}
		groups: {
			/**
			 * I​g​r​e​j​a
			 */
			church: string
			/**
			 * C​o​m​u​n​i​d​a​d​e
			 */
			community: string
			/**
			 * E​x​t​e​r​n​o
			 */
			external: string
		}
	}
	edit: {
		/**
		 * F​a​m​í​l​i​a​s​ ​O​f​e​r​t​a​n​t​e​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​F​a​m​í​l​i​a​ ​O​f​e​r​t​a​n​t​e
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * C​o​m​p​r​o​m​i​s​s​o
			 */
			commitmentLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * G​r​u​p​o
			 */
			groupLabel: string
		}
		groups: {
			/**
			 * I​g​r​e​j​a
			 */
			church: string
			/**
			 * C​o​m​u​n​i​d​a​d​e
			 */
			community: string
			/**
			 * E​x​t​e​r​n​o
			 */
			external: string
		}
	}
}

export type NamespaceProfileTranslation = {
	/**
	 * P​e​r​f​i​l
	 */
	pageTitle: string
	appHeader: {
		/**
		 * P​e​r​f​i​l
		 */
		name: string
		/**
		 * S​a​l​v​a​r
		 */
		buttonText: string
	}
	roles: {
		/**
		 * V​o​l​u​n​t​á​r​i​o
		 */
		volunteer: string
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * W​e​b​ ​M​a​s​t​e​r
		 */
		webMaster: string
	}
	inputs: {
		/**
		 * P​r​i​m​e​i​r​o​ ​N​o​m​e
		 */
		firstNameLabel: string
		/**
		 * Ú​l​t​i​m​o​ ​N​o​m​e
		 */
		lastNameLabel: string
		/**
		 * E​-​m​a​i​l
		 */
		emailLabel: string
		/**
		 * S​e​n​h​a
		 */
		passwordLabel: string
		/**
		 * R​e​p​i​t​a​ ​a​ ​S​e​n​h​a
		 */
		confirmPasswordLabel: string
		/**
		 * A​c​e​s​s​o
		 */
		roleLabel: string
	}
	yupMessages: {
		/**
		 * A​s​ ​s​e​n​h​a​s​ ​d​e​v​e​m​ ​s​e​r​ ​i​g​u​a​i​s
		 */
		confirmPassword: string
	}
	profilePic: {
		/**
		 * I​m​a​g​e​m​ ​d​e​ ​p​e​r​f​i​l
		 */
		altText: string
		/**
		 * E​d​i​t​a​r
		 */
		editText: string
	}
}

export type NamespaceReportsTranslation = {
	list: {
		/**
		 * R​e​l​a​t​ó​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * R​e​l​a​t​ó​r​i​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​R​e​l​a​t​ó​r​i​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o​ ​C​u​r​t​a
			 */
			shortDescriptionLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
	}
	add: {
		/**
		 * R​e​l​a​t​ó​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​R​e​l​a​t​ó​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o​ ​C​u​r​t​a
			 */
			shortDescriptionLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
		reportTypes: {
			/**
			 * C​o​m​u​m
			 */
			ordinary: string
			/**
			 * S​e​m​e​s​t​r​a​l
			 */
			semester: string
			/**
			 * A​n​u​a​l
			 */
			annual: string
		}
	}
	edit: {
		/**
		 * R​e​l​a​t​ó​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​R​e​l​a​t​ó​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * T​í​t​u​l​o
			 */
			titleLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
			/**
			 * D​e​s​c​r​i​ç​ã​o​ ​C​u​r​t​a
			 */
			shortDescriptionLabel: string
			/**
			 * A​n​e​x​o​s
			 */
			attachmentsLabel: string
			/**
			 * M​ê​s
			 */
			monthLabel: string
			/**
			 * A​n​o
			 */
			yearLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
		}
		reportTypes: {
			/**
			 * C​o​m​u​m
			 */
			ordinary: string
			/**
			 * S​e​m​e​s​t​r​a​l
			 */
			semester: string
			/**
			 * A​n​u​a​l
			 */
			annual: string
		}
	}
}

export type NamespaceSharedTranslation = {
	collectionHeader: {
		/**
		 * C​r​i​a​d​o​ ​E​m
		 */
		createdAtLabel: string
		/**
		 * A​t​u​a​l​i​z​a​d​o​ ​E​m
		 */
		updatedAtLabel: string
		/**
		 * D​e​l​e​t​a​d​o​ ​E​m
		 */
		deletedLabel: string
	}
	remove: {
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​a​ ​c​o​n​t​a​ ​d​e​ ​{​e​m​a​i​l​}​?
		 * @param {string} email
		 */
		users: RequiredParams<'email'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​a​r​q​u​i​v​o​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		files: RequiredParams<'name'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​l​o​g​ ​d​e​ ​{​c​r​e​a​t​e​d​A​t​}​?
		 * @param {string} createdAt
		 */
		logs: RequiredParams<'createdAt'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​e​v​e​n​t​o​ ​{​t​i​t​l​e​}​?
		 * @param {string} title
		 */
		agenda: RequiredParams<'title'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​a​n​ú​n​c​i​o​ ​{​t​i​t​l​e​}​?
		 * @param {string} title
		 */
		announcements: RequiredParams<'title'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​t​e​s​t​e​m​u​n​h​o​ ​d​e​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		testimonials: RequiredParams<'name'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​r​e​l​a​t​ó​r​i​o​ ​{​t​i​t​l​e​}​?
		 * @param {string} title
		 */
		reports: RequiredParams<'title'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​a​ ​f​a​m​í​l​i​a​ ​o​f​e​r​t​a​n​t​e​ ​r​e​p​r​e​s​e​n​t​a​d​a​ ​p​e​l​o​(​a​)​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		'offeror-families': RequiredParams<'name'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​a​ ​f​a​m​í​l​i​a​ ​a​c​o​l​h​i​d​a​ ​r​e​p​r​e​s​e​n​t​a​d​a​ ​p​e​l​o​(​a​)​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		'welcomed-families': RequiredParams<'name'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​c​a​m​p​o​ ​m​i​s​s​i​o​n​á​r​i​o​ ​{​d​e​s​i​g​n​a​t​i​o​n​}​?
		 * @param {string} designation
		 */
		fields: RequiredParams<'designation'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​a​ ​i​g​r​e​j​a​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		churches: RequiredParams<'name'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​c​o​l​a​b​o​r​a​d​o​r​ ​{​t​i​t​l​e​}​?
		 * @param {string} title
		 */
		collaborators: RequiredParams<'title'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​a​ ​o​f​e​r​t​a​ ​c​o​l​e​t​a​d​a​ ​d​e​ ​{​m​o​n​t​h​}​/​{​y​e​a​r​}​?
		 * @param {number} month
		 * @param {number} year
		 */
		'collected-offers': RequiredParams<'month' | 'year'>
		/**
		 * V​o​c​ê​ ​d​e​s​e​j​a​ ​r​e​m​o​v​e​r​ ​o​ ​v​o​l​u​n​t​á​r​i​o​ ​{​n​a​m​e​}​?
		 * @param {string} name
		 */
		volunteers: RequiredParams<'name'>
	}
	isStatusTransform: {
		/**
		 * S​i​m
		 */
		'true': string
		/**
		 * N​ã​o
		 */
		'false': string
	}
	yup: {
		/**
		 * {​f​i​e​l​d​}​ ​é​ ​u​m​ ​c​a​m​p​o​ ​o​b​r​i​g​a​t​ó​r​i​o​.
		 * @param {string} field
		 */
		required: RequiredParams<'field'>
		/**
		 * V​o​c​ê​ ​d​e​v​e​ ​e​s​c​o​h​e​r​ ​u​m​ ​d​e​n​t​r​e​ ​o​s​ ​v​a​l​o​r​e​s​:​ ​{​e​n​u​m​s​}​.
		 * @param {string} enums
		 */
		oneOf: RequiredParams<'enums'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​í​n​i​m​o​ ​{​l​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s​.
		 * @param {string} field
		 * @param {number} length
		 */
		min: RequiredParams<'field' | 'length'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​l​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s​.
		 * @param {string} field
		 * @param {number} length
		 */
		max: RequiredParams<'field' | 'length'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​s​e​r​ ​n​o​ ​m​í​n​i​m​o​ ​{​v​a​l​u​e​}​.
		 * @param {string} field
		 * @param {number} value
		 */
		minNumber: RequiredParams<'field' | 'value'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​s​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​v​a​l​u​e​}​.
		 * @param {string} field
		 * @param {number} value
		 */
		maxNumber: RequiredParams<'field' | 'value'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o​ ​v​á​l​i​d​o​.
		 * @param {string} field
		 */
		number: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o​ ​i​n​t​e​i​r​o​.
		 * @param {string} field
		 */
		integer: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​e​-​m​a​i​l​ ​v​á​l​i​d​o​.
		 * @param {string} field
		 */
		email: RequiredParams<'field'>
	}
	axios: {
		/**
		 * O​s​ ​a​r​q​u​i​v​o​s​ ​s​ã​o​ ​m​u​i​t​o​ ​g​r​a​n​d​e​s​!
		 */
		fileSizeError: string
		/**
		 * S​e​r​v​i​d​o​r​ ​n​ã​o​ ​e​s​t​á​ ​d​i​s​p​o​n​í​v​e​l
		 */
		serverNotAvailable: string
	}
	inputs: {
		/**
		 * C​a​m​p​o​ ​M​i​s​s​i​o​n​á​r​i​o
		 */
		fieldLabel: string
	}
	inputFile: {
		/**
		 * E​s​c​o​l​h​e​r​ ​A​r​q​u​i​v​o
		 */
		chooseFile: string
		/**
		 * E​s​c​o​l​h​e​r​ ​A​r​q​u​i​v​o​s
		 */
		chooseFiles: string
	}
}

export type NamespaceSignupTranslation = {
	/**
	 * C​r​i​a​r​ ​C​o​n​t​a
	 */
	pageTitle: string
	authModal: {
		'0': {
			/**
			 * C​r​i​a​r​ ​C​o​n​t​a
			 */
			title: string
			/**
			 * P​o​r​ ​f​a​v​o​r​,​ ​i​n​s​i​r​a​ ​s​e​u​ ​e​-​m​a​i​l
			 */
			subTitle: string
			/**
			 * P​r​ó​x​i​m​o
			 */
			buttonText: string
		}
		'1': {
			/**
			 * V​e​r​i​f​i​c​a​ç​ã​o
			 */
			title: string
			/**
			 * D​i​g​i​t​e​ ​o​ ​s​e​u​ ​t​o​k​e​n
			 */
			subTitle: string
			/**
			 * V​a​l​i​d​a​r
			 */
			buttonText: string
		}
		'2': {
			/**
			 * Ú​l​t​i​m​o​ ​P​a​s​s​o
			 */
			title: string
			/**
			 * P​r​e​e​n​c​h​a​ ​o​s​ ​d​a​d​o​s​ ​f​a​l​t​a​n​t​e​s
			 */
			subTitle: string
			/**
			 * C​r​i​a​r​ ​C​o​n​t​a
			 */
			buttonText: string
		}
	}
	inputs: {
		/**
		 * E​-​m​a​i​l
		 */
		emailLabel: string
		/**
		 * T​o​k​e​n
		 */
		tokenLabel: string
		/**
		 * P​r​i​m​e​i​r​o​ ​N​o​m​e
		 */
		firstNameLabel: string
		/**
		 * Ú​l​t​i​m​o​ ​N​o​m​e
		 */
		lastNameLabel: string
		/**
		 * S​e​n​h​a
		 */
		passwordLabel: string
		/**
		 * R​e​p​i​t​a​ ​a​ ​s​e​n​h​a
		 */
		confirmPasswordLabel: string
	}
	yupMessages: {
		/**
		 * A​p​e​n​a​s​ ​d​í​g​i​t​o​s​ ​a​l​f​a​n​u​m​é​r​i​c​o​s​ ​s​ã​o​ ​v​á​l​i​d​o​s
		 */
		tokenMatch: string
		/**
		 * T​o​k​e​n​ ​i​n​v​á​l​i​d​o​!
		 */
		tokenInvalid: string
		/**
		 * A​s​ ​s​e​n​h​a​s​ ​d​e​v​e​m​ ​s​e​r​ ​i​g​u​a​i​s
		 */
		confirmPassword: string
	}
	links: {
		/**
		 * L​o​g​i​n
		 */
		loginText: string
		/**
		 * R​e​c​u​p​e​r​a​r​ ​C​o​n​t​a
		 */
		forgotPasswordText: string
	}
}

export type NamespaceTestimonialsTranslation = {
	list: {
		/**
		 * T​e​s​t​e​m​u​n​h​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * T​e​s​t​e​m​u​n​h​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​T​e​s​t​e​m​u​n​h​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
		}
	}
	add: {
		/**
		 * T​e​s​t​e​m​u​n​h​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​T​e​s​t​e​m​u​n​h​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
		}
	}
	edit: {
		/**
		 * T​e​s​t​e​m​u​n​h​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​T​e​s​t​e​m​u​n​h​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * T​e​x​t​o
			 */
			textLabel: string
		}
	}
}

export type NamespaceToastTranslation = {
	/**
	 * F​e​c​h​a​r
	 */
	closeText: string
}

export type NamespaceTokensTranslation = {
	list: {
		/**
		 * T​o​k​e​n​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * T​o​k​e​n​s
			 */
			name: string
		}
		collectionHeader: {
			/**
			 * T​o​k​e​n
			 */
			tokenLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * U​s​a​d​o
			 */
			usedLabel: string
			/**
			 * T​i​p​o
			 */
			typeLabel: string
			/**
			 * P​a​y​l​o​a​d
			 */
			payloadLabel: string
			/**
			 * E​x​p​i​r​a​ç​ã​o
			 */
			expirationLabel: string
		}
	}
}

export type NamespaceUsersTranslation = {
	list: {
		/**
		 * U​s​u​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * U​s​u​á​r​i​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​U​s​u​á​r​i​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * A​c​e​s​s​o
			 */
			roleLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​A​c​e​s​s​o
			 */
			lastAccessLabel: string
		}
		/**
		 * (​n​ã​o​ ​i​n​f​o​r​m​a​d​o​)
		 */
		lastNamePlaceholder: string
	}
	add: {
		/**
		 * U​s​u​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​U​s​u​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * A​c​e​s​s​o
			 */
			roleLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​A​c​e​s​s​o
			 */
			lastAccessLabel: string
		}
		roles: {
			/**
			 * V​o​l​u​n​t​á​r​i​o
			 */
			volunteer: string
			/**
			 * A​d​m​i​n
			 */
			admin: string
			/**
			 * W​e​b​ ​M​a​s​t​e​r
			 */
			webMaster: string
		}
		profilePic: {
			/**
			 * I​m​a​g​e​m​ ​d​e​ ​P​e​r​f​i​l
			 */
			altText: string
			/**
			 * E​d​i​t​a​r
			 */
			editText: string
		}
	}
	edit: {
		/**
		 * U​s​u​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​U​s​u​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * A​c​e​s​s​o
			 */
			roleLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​A​c​e​s​s​o
			 */
			lastAccessLabel: string
		}
		roles: {
			/**
			 * V​o​l​u​n​t​á​r​i​o
			 */
			volunteer: string
			/**
			 * A​d​m​i​n
			 */
			admin: string
			/**
			 * W​e​b​ ​M​a​s​t​e​r
			 */
			webMaster: string
		}
		profilePic: {
			/**
			 * I​m​a​g​e​m​ ​d​e​ ​P​e​r​f​i​l
			 */
			altText: string
			/**
			 * E​d​i​t​a​r
			 */
			editText: string
		}
	}
}

export type NamespaceVolunteersTranslation = {
	list: {
		/**
		 * V​o​l​u​n​t​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * V​o​l​u​n​t​á​r​i​o​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​V​o​l​u​n​t​á​r​i​o
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * D​a​t​a​ ​d​e​ ​A​d​m​i​s​s​ã​o
			 */
			joinedDateLabel: string
			/**
			 * O​c​u​p​a​ç​ã​o
			 */
			occupationLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * P​a​s​t​o​r
			 */
			priestLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
	}
	add: {
		/**
		 * V​o​l​u​n​t​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​V​o​l​u​n​t​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * D​a​t​a​ ​d​e​ ​A​d​m​i​s​s​ã​o
			 */
			joinedDateLabel: string
			/**
			 * O​c​u​p​a​ç​ã​o
			 */
			occupationLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * P​a​s​t​o​r
			 */
			priestLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
		occupations: {
			/**
			 * P​r​e​s​i​d​e​n​t​e
			 */
			president: string
			/**
			 * V​i​c​e​-​P​r​e​s​i​d​e​n​t​e
			 */
			vicePresident: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​G​e​r​a​l
			 */
			geralCoordinator: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​0​1
			 */
			coordinator01: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​1
			 */
			counselor01: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​2
			 */
			counselor02: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​3
			 */
			counselor03: string
			/**
			 * W​e​b​ ​M​a​s​t​e​r
			 */
			webMaster: string
			/**
			 * T​e​s​o​u​r​e​i​r​o​ ​0​1
			 */
			treasurer01: string
			/**
			 * T​e​s​o​u​r​e​i​r​o​ ​0​2
			 */
			treasurer02: string
			/**
			 * I​n​s​t​r​u​t​o​r​ ​A​c​a​d​ê​m​i​c​o​ ​0​1
			 */
			academicInstructor01: string
			/**
			 * I​n​s​t​r​u​t​o​r​ ​A​c​a​d​ê​m​i​c​o​ ​0​2
			 */
			academicInstructor02: string
			/**
			 * S​e​c​r​e​t​á​r​i​o​(​a​)​ ​E​x​e​c​u​t​i​v​(​o​)
			 */
			executiveSecretary: string
			/**
			 * S​e​c​r​e​t​á​r​i​o​(​a​)​ ​A​u​x​i​l​i​a​r
			 */
			auxiliarySecretary: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​0​2
			 */
			coordinator02: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​I​n​t​e​r​n​o
			 */
			infieldCoordinator: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​E​x​t​e​r​n​o
			 */
			outfieldCoordinator: string
			/**
			 * C​o​l​e​t​o​r
			 */
			collector: string
			/**
			 * S​e​r​v​i​ç​o​ ​d​e​ ​A​p​o​i​o
			 */
			supportService: string
		}
		profilePic: {
			/**
			 * I​m​a​g​e​m​ ​d​e​ ​P​e​r​f​i​l
			 */
			altText: string
			/**
			 * E​d​i​t​a​r
			 */
			editText: string
		}
	}
	edit: {
		/**
		 * V​o​l​u​n​t​á​r​i​o​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​V​o​l​u​n​t​á​r​i​o
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * N​o​m​e
			 */
			nameLabel: string
			/**
			 * P​r​i​m​e​i​r​o​ ​N​o​m​e
			 */
			firstNameLabel: string
			/**
			 * Ú​l​t​i​m​o​ ​N​o​m​e
			 */
			lastNameLabel: string
			/**
			 * E​-​m​a​i​l
			 */
			emailLabel: string
			/**
			 * D​a​t​a​ ​d​e​ ​A​d​m​i​s​s​ã​o
			 */
			joinedDateLabel: string
			/**
			 * O​c​u​p​a​ç​ã​o
			 */
			occupationLabel: string
			/**
			 * I​g​r​e​j​a
			 */
			churchLabel: string
			/**
			 * P​a​s​t​o​r
			 */
			priestLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
		occupations: {
			/**
			 * P​r​e​s​i​d​e​n​t​e
			 */
			president: string
			/**
			 * V​i​c​e​-​P​r​e​s​i​d​e​n​t​e
			 */
			vicePresident: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​G​e​r​a​l
			 */
			geralCoordinator: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​0​1
			 */
			coordinator01: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​1
			 */
			counselor01: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​2
			 */
			counselor02: string
			/**
			 * C​o​n​s​e​l​h​e​i​r​o​ ​0​3
			 */
			counselor03: string
			/**
			 * W​e​b​ ​M​a​s​t​e​r
			 */
			webMaster: string
			/**
			 * T​e​s​o​u​r​e​i​r​o​ ​0​1
			 */
			treasurer01: string
			/**
			 * T​e​s​o​u​r​e​i​r​o​ ​0​2
			 */
			treasurer02: string
			/**
			 * I​n​s​t​r​u​t​o​r​ ​A​c​a​d​ê​m​i​c​o​ ​0​1
			 */
			academicInstructor01: string
			/**
			 * I​n​s​t​r​u​t​o​r​ ​A​c​a​d​ê​m​i​c​o​ ​0​2
			 */
			academicInstructor02: string
			/**
			 * S​e​c​r​e​t​á​r​i​o​(​a​)​ ​E​x​e​c​u​t​i​v​(​o​)
			 */
			executiveSecretary: string
			/**
			 * S​e​c​r​e​t​á​r​i​o​(​a​)​ ​A​u​x​i​l​i​a​r
			 */
			auxiliarySecretary: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​0​2
			 */
			coordinator02: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​I​n​t​e​r​n​o
			 */
			infieldCoordinator: string
			/**
			 * C​o​o​r​d​e​n​a​d​o​r​ ​E​x​t​e​r​n​o
			 */
			outfieldCoordinator: string
			/**
			 * C​o​l​e​t​o​r
			 */
			collector: string
			/**
			 * S​e​r​v​i​ç​o​ ​d​e​ ​A​p​o​i​o
			 */
			supportService: string
		}
		profilePic: {
			/**
			 * I​m​a​g​e​m​ ​d​e​ ​P​e​r​f​i​l
			 */
			altText: string
			/**
			 * E​d​i​t​a​r
			 */
			editText: string
		}
	}
}

export type NamespaceWelcomedFamiliesTranslation = {
	list: {
		/**
		 * F​a​m​í​l​i​a​s​ ​A​c​o​l​h​i​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * F​a​m​í​l​i​a​s​ ​A​c​o​l​h​i​d​a​s
			 */
			name: string
			/**
			 * A​d​i​c​i​o​n​a​r​ ​F​a​m​í​l​i​a​ ​A​c​o​l​h​i​d​a
			 */
			buttonText: string
		}
		collectionHeader: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
	}
	add: {
		/**
		 * F​a​m​í​l​i​a​s​ ​A​c​o​l​h​i​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * A​d​i​c​i​o​n​a​r​ ​F​a​m​í​l​i​a​ ​A​c​o​l​h​i​d​a
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
	}
	edit: {
		/**
		 * F​a​m​í​l​i​a​s​ ​A​c​o​l​h​i​d​a​s
		 */
		pageTitle: string
		appHeader: {
			/**
			 * E​d​i​t​a​r​ ​F​a​m​í​l​i​a​ ​A​c​o​l​h​i​d​a
			 */
			name: string
			/**
			 * S​a​l​v​a​r
			 */
			buttonText: string
		}
		inputs: {
			/**
			 * R​e​p​r​e​s​e​n​t​a​n​t​e
			 */
			representativeLabel: string
			/**
			 * O​b​s​e​r​v​a​ç​ã​o
			 */
			observationLabel: string
		}
	}
}

export type Namespaces =
	| 'agenda'
	| 'announcements'
	| 'app-actions'
	| 'app-header'
	| 'app-nav'
	| 'churches'
	| 'collaborators'
	| 'collected-offers'
	| 'collection-header'
	| 'collection-row'
	| 'collection-row-placeholder'
	| 'dashboard'
	| 'fields'
	| 'files'
	| 'forgot-password'
	| 'login'
	| 'logs'
	| 'offeror-families'
	| 'profile'
	| 'reports'
	| 'shared'
	| 'signup'
	| 'testimonials'
	| 'toast'
	| 'tokens'
	| 'users'
	| 'volunteers'
	| 'welcomed-families'

type DisallowNamespaces = {
	/**
	 * reserved for 'agenda'-namespace\
	 * you need to use the `./agenda/index.ts` file instead
	 */
	agenda?: "[typesafe-i18n] reserved for 'agenda'-namespace. You need to use the `./agenda/index.ts` file instead."

	/**
	 * reserved for 'announcements'-namespace\
	 * you need to use the `./announcements/index.ts` file instead
	 */
	announcements?: "[typesafe-i18n] reserved for 'announcements'-namespace. You need to use the `./announcements/index.ts` file instead."

	/**
	 * reserved for 'app-actions'-namespace\
	 * you need to use the `./app-actions/index.ts` file instead
	 */
	'app-actions'?: "[typesafe-i18n] reserved for 'app-actions'-namespace. You need to use the `./app-actions/index.ts` file instead."

	/**
	 * reserved for 'app-header'-namespace\
	 * you need to use the `./app-header/index.ts` file instead
	 */
	'app-header'?: "[typesafe-i18n] reserved for 'app-header'-namespace. You need to use the `./app-header/index.ts` file instead."

	/**
	 * reserved for 'app-nav'-namespace\
	 * you need to use the `./app-nav/index.ts` file instead
	 */
	'app-nav'?: "[typesafe-i18n] reserved for 'app-nav'-namespace. You need to use the `./app-nav/index.ts` file instead."

	/**
	 * reserved for 'churches'-namespace\
	 * you need to use the `./churches/index.ts` file instead
	 */
	churches?: "[typesafe-i18n] reserved for 'churches'-namespace. You need to use the `./churches/index.ts` file instead."

	/**
	 * reserved for 'collaborators'-namespace\
	 * you need to use the `./collaborators/index.ts` file instead
	 */
	collaborators?: "[typesafe-i18n] reserved for 'collaborators'-namespace. You need to use the `./collaborators/index.ts` file instead."

	/**
	 * reserved for 'collected-offers'-namespace\
	 * you need to use the `./collected-offers/index.ts` file instead
	 */
	'collected-offers'?: "[typesafe-i18n] reserved for 'collected-offers'-namespace. You need to use the `./collected-offers/index.ts` file instead."

	/**
	 * reserved for 'collection-header'-namespace\
	 * you need to use the `./collection-header/index.ts` file instead
	 */
	'collection-header'?: "[typesafe-i18n] reserved for 'collection-header'-namespace. You need to use the `./collection-header/index.ts` file instead."

	/**
	 * reserved for 'collection-row'-namespace\
	 * you need to use the `./collection-row/index.ts` file instead
	 */
	'collection-row'?: "[typesafe-i18n] reserved for 'collection-row'-namespace. You need to use the `./collection-row/index.ts` file instead."

	/**
	 * reserved for 'collection-row-placeholder'-namespace\
	 * you need to use the `./collection-row-placeholder/index.ts` file instead
	 */
	'collection-row-placeholder'?: "[typesafe-i18n] reserved for 'collection-row-placeholder'-namespace. You need to use the `./collection-row-placeholder/index.ts` file instead."

	/**
	 * reserved for 'dashboard'-namespace\
	 * you need to use the `./dashboard/index.ts` file instead
	 */
	dashboard?: "[typesafe-i18n] reserved for 'dashboard'-namespace. You need to use the `./dashboard/index.ts` file instead."

	/**
	 * reserved for 'fields'-namespace\
	 * you need to use the `./fields/index.ts` file instead
	 */
	fields?: "[typesafe-i18n] reserved for 'fields'-namespace. You need to use the `./fields/index.ts` file instead."

	/**
	 * reserved for 'files'-namespace\
	 * you need to use the `./files/index.ts` file instead
	 */
	files?: "[typesafe-i18n] reserved for 'files'-namespace. You need to use the `./files/index.ts` file instead."

	/**
	 * reserved for 'forgot-password'-namespace\
	 * you need to use the `./forgot-password/index.ts` file instead
	 */
	'forgot-password'?: "[typesafe-i18n] reserved for 'forgot-password'-namespace. You need to use the `./forgot-password/index.ts` file instead."

	/**
	 * reserved for 'login'-namespace\
	 * you need to use the `./login/index.ts` file instead
	 */
	login?: "[typesafe-i18n] reserved for 'login'-namespace. You need to use the `./login/index.ts` file instead."

	/**
	 * reserved for 'logs'-namespace\
	 * you need to use the `./logs/index.ts` file instead
	 */
	logs?: "[typesafe-i18n] reserved for 'logs'-namespace. You need to use the `./logs/index.ts` file instead."

	/**
	 * reserved for 'offeror-families'-namespace\
	 * you need to use the `./offeror-families/index.ts` file instead
	 */
	'offeror-families'?: "[typesafe-i18n] reserved for 'offeror-families'-namespace. You need to use the `./offeror-families/index.ts` file instead."

	/**
	 * reserved for 'profile'-namespace\
	 * you need to use the `./profile/index.ts` file instead
	 */
	profile?: "[typesafe-i18n] reserved for 'profile'-namespace. You need to use the `./profile/index.ts` file instead."

	/**
	 * reserved for 'reports'-namespace\
	 * you need to use the `./reports/index.ts` file instead
	 */
	reports?: "[typesafe-i18n] reserved for 'reports'-namespace. You need to use the `./reports/index.ts` file instead."

	/**
	 * reserved for 'shared'-namespace\
	 * you need to use the `./shared/index.ts` file instead
	 */
	shared?: "[typesafe-i18n] reserved for 'shared'-namespace. You need to use the `./shared/index.ts` file instead."

	/**
	 * reserved for 'signup'-namespace\
	 * you need to use the `./signup/index.ts` file instead
	 */
	signup?: "[typesafe-i18n] reserved for 'signup'-namespace. You need to use the `./signup/index.ts` file instead."

	/**
	 * reserved for 'testimonials'-namespace\
	 * you need to use the `./testimonials/index.ts` file instead
	 */
	testimonials?: "[typesafe-i18n] reserved for 'testimonials'-namespace. You need to use the `./testimonials/index.ts` file instead."

	/**
	 * reserved for 'toast'-namespace\
	 * you need to use the `./toast/index.ts` file instead
	 */
	toast?: "[typesafe-i18n] reserved for 'toast'-namespace. You need to use the `./toast/index.ts` file instead."

	/**
	 * reserved for 'tokens'-namespace\
	 * you need to use the `./tokens/index.ts` file instead
	 */
	tokens?: "[typesafe-i18n] reserved for 'tokens'-namespace. You need to use the `./tokens/index.ts` file instead."

	/**
	 * reserved for 'users'-namespace\
	 * you need to use the `./users/index.ts` file instead
	 */
	users?: "[typesafe-i18n] reserved for 'users'-namespace. You need to use the `./users/index.ts` file instead."

	/**
	 * reserved for 'volunteers'-namespace\
	 * you need to use the `./volunteers/index.ts` file instead
	 */
	volunteers?: "[typesafe-i18n] reserved for 'volunteers'-namespace. You need to use the `./volunteers/index.ts` file instead."

	/**
	 * reserved for 'welcomed-families'-namespace\
	 * you need to use the `./welcomed-families/index.ts` file instead
	 */
	'welcomed-families'?: "[typesafe-i18n] reserved for 'welcomed-families'-namespace. You need to use the `./welcomed-families/index.ts` file instead."
}

export type TranslationFunctions = {
	agenda: {
		list: {
			/**
			 * Agenda
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Agenda
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Evento
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Data
				 */
				dateLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Agenda
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Evento
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Data
				 */
				dateLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Agenda
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Evento
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Data
				 */
				dateLabel: () => LocalizedString
			}
		}
	}
	announcements: {
		list: {
			/**
			 * Anúncios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Anúncios
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Anúncio
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Fixado
				 */
				fixedLabel: () => LocalizedString
				/**
				 * Sim
				 */
				yes: () => LocalizedString
				/**
				 * Não
				 */
				no: () => LocalizedString
			}
		}
		add: {
			/**
			 * Anúncios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Anúncio
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Fixado
				 */
				fixedLabel: () => LocalizedString
				/**
				 * Sim
				 */
				yes: () => LocalizedString
				/**
				 * Não
				 */
				no: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Anúncios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Anúncio
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Mensagem
				 */
				messageLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Fixado
				 */
				fixedLabel: () => LocalizedString
				/**
				 * Sim
				 */
				yes: () => LocalizedString
				/**
				 * Não
				 */
				no: () => LocalizedString
			}
		}
	}
	'app-actions': {
		/**
		 * Pesquise Aqui...
		 */
		searchInputPlaceHolder: () => LocalizedString
		/**
		 * Número total de items
		 */
		totalItemsTitle: () => LocalizedString
		/**
		 * Items
		 */
		totalItemsText: () => LocalizedString
		/**
		 * Filtro
		 */
		filterIconText: () => LocalizedString
		/**
		 * Campo Missionário
		 */
		filterFieldLabel: () => LocalizedString
		/**
		 * Reiniciar
		 */
		filterResetButton: () => LocalizedString
		/**
		 * Aplicar
		 */
		filterApplyButton: () => LocalizedString
		/**
		 * Visualizar em lista
		 */
		listViewTitle: () => LocalizedString
		/**
		 * Visualizar em grid
		 */
		gridViewTitle: () => LocalizedString
		/**
		 * Mostrar Deletados
		 */
		showDeletedText: () => LocalizedString
		/**
		 * Restaurar Selecionados
		 */
		showDeletedRestoreButton: () => LocalizedString
		/**
		 * Remover Selecionados
		 */
		showDeletedHardRemoveButton: () => LocalizedString
	}
	'app-header': {
		/**
		 * Atualizar
		 */
		refreshButtonTitle: () => LocalizedString
		/**
		 * Alternar Tema
		 */
		switchThemeButtonTitle: () => LocalizedString
	}
	'app-nav': {
		menu: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * Agenda
			 */
			agenda: () => LocalizedString
			/**
			 * Anúncios
			 */
			announcements: () => LocalizedString
			/**
			 * Igrejas
			 */
			churches: () => LocalizedString
			/**
			 * Colaboradores
			 */
			collaborators: () => LocalizedString
			/**
			 * Ofertas Coletadas
			 */
			collectedOffers: () => LocalizedString
			/**
			 * Campos Missionários
			 */
			fields: () => LocalizedString
			/**
			 * Arquivos
			 */
			files: () => LocalizedString
			/**
			 * Logs
			 */
			logs: () => LocalizedString
			/**
			 * Famílias Ofertantes
			 */
			offerorFamilies: () => LocalizedString
			/**
			 * Relatórios
			 */
			reports: () => LocalizedString
			/**
			 * Testemunhos
			 */
			testimonials: () => LocalizedString
			/**
			 * Tokens
			 */
			tokens: () => LocalizedString
			/**
			 * Usuários
			 */
			users: () => LocalizedString
			/**
			 * Voluntários
			 */
			volunteers: () => LocalizedString
			/**
			 * Famílias Acolhidas
			 */
			welcomedFamilies: () => LocalizedString
		}
		accountMenu: {
			links: {
				/**
				 * Perfil
				 */
				profile: () => LocalizedString
				/**
				 * Logout
				 */
				logout: () => LocalizedString
			}
		}
		/**
		 * Olá, {name}.
		 */
		userMessage: (arg: { name: string }) => LocalizedString
	}
	churches: {
		list: {
			/**
			 * Igrejas em Unidade
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Igrejas em Unidade
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Igreja em Unidade
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagens
				 */
				imagesLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Igrejas em Unidade
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Igreja em Unidade
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagens
				 */
				imagesLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
			churchTypes: {
				/**
				 * Pioneira
				 */
				pioneer: () => LocalizedString
				/**
				 * Expansionista
				 */
				expansion: () => LocalizedString
				/**
				 * Apoio
				 */
				support: () => LocalizedString
				/**
				 * Responsável
				 */
				responsible: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Igrejas em Unidade
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Igreja em unidade
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagens
				 */
				imagesLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
			churchTypes: {
				/**
				 * Pioneira
				 */
				pioneer: () => LocalizedString
				/**
				 * Expansionista
				 */
				expansion: () => LocalizedString
				/**
				 * Apoio
				 */
				support: () => LocalizedString
				/**
				 * Responsável
				 */
				responsible: () => LocalizedString
			}
		}
	}
	collaborators: {
		list: {
			/**
			 * Colaboradores
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Colaboradores
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Colaborador
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagem
				 */
				imageLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Colaboradores
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Colaborador
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagem
				 */
				imageLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Colaboradores
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Colaborador
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Descrição
				 */
				descriptionLabel: () => LocalizedString
				/**
				 * Imagem
				 */
				imageLabel: () => LocalizedString
			}
		}
	}
	'collected-offers': {
		list: {
			/**
			 * Ofertas Coletadas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Ofertas Coletadas
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Ofertas Coletadas
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Mantimentos (Qnt.)
				 */
				foodQntLabel: () => LocalizedString
				/**
				 * Valor
				 */
				monetaryValueLabel: () => LocalizedString
				/**
				 * Outros (Qnt.)
				 */
				othersQntLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Ofertas Coletadas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Ofertas Coletadas
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Mantimentos (Qnt.)
				 */
				foodQntLabel: () => LocalizedString
				/**
				 * Valor
				 */
				monetaryValueLabel: () => LocalizedString
				/**
				 * Outros (Qnt.)
				 */
				othersQntLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Ofertas Coletadas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Ofertas Coletadas
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Mantimentos (Qnt.)
				 */
				foodQntLabel: () => LocalizedString
				/**
				 * Valor
				 */
				monetaryValueLabel: () => LocalizedString
				/**
				 * Outros (Qnt.)
				 */
				othersQntLabel: () => LocalizedString
			}
		}
	}
	'collection-header': {
		/**
		 * Opções
		 */
		optionsColumnText: () => LocalizedString
		/**
		 * Selecionar
		 */
		selectionColumnText: () => LocalizedString
	}
	'collection-row': {
		/**
		 * Ativo
		 */
		isStatusActiveText: () => LocalizedString
		/**
		 * Desativado
		 */
		isStatusDisabledText: () => LocalizedString
		/**
		 * NÃO DELETADO
		 */
		notDeletedText: () => LocalizedString
		/**
		 * Editar
		 */
		editButtonTitle: () => LocalizedString
		/**
		 * Remover
		 */
		removeButtonTitle: () => LocalizedString
	}
	'collection-row-placeholder': {
		/**
		 * Parece que ainda não há nenhum registro...
		 */
		description: () => LocalizedString
	}
	dashboard: {
		/**
		 * Dashboard
		 */
		pageTitle: () => LocalizedString
		appHeader: {
			/**
			 * Dashboard
			 */
			name: () => LocalizedString
		}
		/**
		 * Bem-vindo, {name}!
		 */
		welcomedText: (arg: { name: string }) => LocalizedString
		/**
		 * Hoje é {date}.
		 */
		todayDate: (arg: { date: string }) => LocalizedString
	}
	fields: {
		list: {
			/**
			 * Campos Missionários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Campos Missionários
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Campo Missionário
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Continente
				 */
				continentLabel: () => LocalizedString
				/**
				 * País
				 */
				countryLabel: () => LocalizedString
				/**
				 * Estado
				 */
				stateLabel: () => LocalizedString
				/**
				 * Abreviação
				 */
				abbreviationLabel: () => LocalizedString
				/**
				 * Designação
				 */
				designationLabel: () => LocalizedString
				/**
				 * Pontos de Coleta
				 */
				collectionPointsLabel: () => LocalizedString
				/**
				 * Relação de Ruas
				 */
				streetRelationLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Campos Missionários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Campo Missionário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Continente
				 */
				continentLabel: () => LocalizedString
				/**
				 * País
				 */
				countryLabel: () => LocalizedString
				/**
				 * Estado
				 */
				stateLabel: () => LocalizedString
				/**
				 * Abreviação
				 */
				abbreviationLabel: () => LocalizedString
				/**
				 * Designação
				 */
				designationLabel: () => LocalizedString
				/**
				 * Pontos de Coleta
				 */
				collectionPointsLabel: () => LocalizedString
				/**
				 * Relação de Ruas
				 */
				streetRelationLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Campos Missionários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Campo Missionário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Continente
				 */
				continentLabel: () => LocalizedString
				/**
				 * País
				 */
				countryLabel: () => LocalizedString
				/**
				 * Estado
				 */
				stateLabel: () => LocalizedString
				/**
				 * Abreviação
				 */
				abbreviationLabel: () => LocalizedString
				/**
				 * Designação
				 */
				designationLabel: () => LocalizedString
				/**
				 * Pontos de Coleta
				 */
				collectionPointsLabel: () => LocalizedString
				/**
				 * Relação de Ruas
				 */
				streetRelationLabel: () => LocalizedString
			}
		}
	}
	files: {
		list: {
			/**
			 * Arquivos
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Arquivos
				 */
				name: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * MimeType
				 */
				mimeTypeLabel: () => LocalizedString
				/**
				 * Tamanho
				 */
				sizeLabel: () => LocalizedString
			}
		}
	}
	'forgot-password': {
		/**
		 * Recuperar Conta
		 */
		pageTitle: () => LocalizedString
		authModal: {
			'0': {
				/**
				 * Recuperar Conta
				 */
				title: () => LocalizedString
				/**
				 * Por favor, insira seu e-mail
				 */
				subTitle: () => LocalizedString
				/**
				 * Próximo
				 */
				buttonText: () => LocalizedString
			}
			'1': {
				/**
				 * Verificação
				 */
				title: () => LocalizedString
				/**
				 * Digite o seu token
				 */
				subTitle: () => LocalizedString
				/**
				 * Validar
				 */
				buttonText: () => LocalizedString
			}
			'2': {
				/**
				 * Último Passo
				 */
				title: () => LocalizedString
				/**
				 * Sua nova senha, por favor
				 */
				subTitle: () => LocalizedString
				/**
				 * Salvar Nova Senha
				 */
				buttonText: () => LocalizedString
			}
		}
		inputs: {
			/**
			 * E-mail
			 */
			emailLabel: () => LocalizedString
			/**
			 * Token
			 */
			tokenLabel: () => LocalizedString
			/**
			 * Senha
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Repita a senha
			 */
			confirmPasswordLabel: () => LocalizedString
		}
		yupMessages: {
			/**
			 * Apenas dígitos alfanuméricos são válidos
			 */
			tokenMatch: () => LocalizedString
			/**
			 * Token inválido!
			 */
			tokenInvalid: () => LocalizedString
			/**
			 * As senhas devem ser iguais
			 */
			confirmPassword: () => LocalizedString
		}
		links: {
			/**
			 * Login
			 */
			loginText: () => LocalizedString
			/**
			 * Criar Conta
			 */
			signupText: () => LocalizedString
		}
	}
	login: {
		/**
		 * Login
		 */
		pageTitle: () => LocalizedString
		authModal: {
			/**
			 * Projeto Um Por Todos! Todos Por Um.
			 */
			title: () => LocalizedString
			/**
			 * Bem-vindo de Volta
			 */
			subTitle: () => LocalizedString
			/**
			 * Entrar
			 */
			buttonText: () => LocalizedString
		}
		inputs: {
			/**
			 * E-mail
			 */
			emailLabel: () => LocalizedString
			/**
			 * Senha
			 */
			passwordLabel: () => LocalizedString
		}
		links: {
			/**
			 * Criar Conta
			 */
			signupText: () => LocalizedString
			/**
			 * Recuperar Conta
			 */
			forgotPasswordText: () => LocalizedString
		}
	}
	logs: {
		list: {
			/**
			 * Logs
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Logs
				 */
				name: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * IP
				 */
				ipLabel: () => LocalizedString
				/**
				 * METHOD
				 */
				methodLabel: () => LocalizedString
				/**
				 * URL
				 */
				urlLabel: () => LocalizedString
				/**
				 * Body
				 */
				bodyLabel: () => LocalizedString
				/**
				 * Arquivos
				 */
				filesLabel: () => LocalizedString
				/**
				 * Query
				 */
				queryLabel: () => LocalizedString
				/**
				 * Código de Status
				 */
				statusCodeLabel: () => LocalizedString
				/**
				 * Usuário
				 */
				userLabel: () => LocalizedString
			}
		}
	}
	'offeror-families': {
		list: {
			/**
			 * Famílias Ofertantes
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Famílias Ofertantes
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Família Ofertante
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Compromisso
				 */
				commitmentLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Grupo
				 */
				groupLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Famílias Ofertantes
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Família Ofertante
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Compromisso
				 */
				commitmentLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Grupo
				 */
				groupLabel: () => LocalizedString
			}
			groups: {
				/**
				 * Igreja
				 */
				church: () => LocalizedString
				/**
				 * Comunidade
				 */
				community: () => LocalizedString
				/**
				 * Externo
				 */
				external: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Famílias Ofertantes
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Família Ofertante
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Compromisso
				 */
				commitmentLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Grupo
				 */
				groupLabel: () => LocalizedString
			}
			groups: {
				/**
				 * Igreja
				 */
				church: () => LocalizedString
				/**
				 * Comunidade
				 */
				community: () => LocalizedString
				/**
				 * Externo
				 */
				external: () => LocalizedString
			}
		}
	}
	profile: {
		/**
		 * Perfil
		 */
		pageTitle: () => LocalizedString
		appHeader: {
			/**
			 * Perfil
			 */
			name: () => LocalizedString
			/**
			 * Salvar
			 */
			buttonText: () => LocalizedString
		}
		roles: {
			/**
			 * Voluntário
			 */
			volunteer: () => LocalizedString
			/**
			 * Admin
			 */
			admin: () => LocalizedString
			/**
			 * Web Master
			 */
			webMaster: () => LocalizedString
		}
		inputs: {
			/**
			 * Primeiro Nome
			 */
			firstNameLabel: () => LocalizedString
			/**
			 * Último Nome
			 */
			lastNameLabel: () => LocalizedString
			/**
			 * E-mail
			 */
			emailLabel: () => LocalizedString
			/**
			 * Senha
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Repita a Senha
			 */
			confirmPasswordLabel: () => LocalizedString
			/**
			 * Acesso
			 */
			roleLabel: () => LocalizedString
		}
		yupMessages: {
			/**
			 * As senhas devem ser iguais
			 */
			confirmPassword: () => LocalizedString
		}
		profilePic: {
			/**
			 * Imagem de perfil
			 */
			altText: () => LocalizedString
			/**
			 * Editar
			 */
			editText: () => LocalizedString
		}
	}
	reports: {
		list: {
			/**
			 * Relatórios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Relatórios
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Relatório
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
				/**
				 * Descrição Curta
				 */
				shortDescriptionLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Relatórios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Relatório
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
				/**
				 * Descrição Curta
				 */
				shortDescriptionLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
			reportTypes: {
				/**
				 * Comum
				 */
				ordinary: () => LocalizedString
				/**
				 * Semestral
				 */
				semester: () => LocalizedString
				/**
				 * Anual
				 */
				annual: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Relatórios
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Relatório
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Título
				 */
				titleLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
				/**
				 * Descrição Curta
				 */
				shortDescriptionLabel: () => LocalizedString
				/**
				 * Anexos
				 */
				attachmentsLabel: () => LocalizedString
				/**
				 * Mês
				 */
				monthLabel: () => LocalizedString
				/**
				 * Ano
				 */
				yearLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
			}
			reportTypes: {
				/**
				 * Comum
				 */
				ordinary: () => LocalizedString
				/**
				 * Semestral
				 */
				semester: () => LocalizedString
				/**
				 * Anual
				 */
				annual: () => LocalizedString
			}
		}
	}
	shared: {
		collectionHeader: {
			/**
			 * Criado Em
			 */
			createdAtLabel: () => LocalizedString
			/**
			 * Atualizado Em
			 */
			updatedAtLabel: () => LocalizedString
			/**
			 * Deletado Em
			 */
			deletedLabel: () => LocalizedString
		}
		remove: {
			/**
			 * Você deseja remover a conta de {email}?
			 */
			users: (arg: { email: string }) => LocalizedString
			/**
			 * Você deseja remover o arquivo {name}?
			 */
			files: (arg: { name: string }) => LocalizedString
			/**
			 * Você deseja remover o log de {createdAt}?
			 */
			logs: (arg: { createdAt: string }) => LocalizedString
			/**
			 * Você deseja remover o evento {title}?
			 */
			agenda: (arg: { title: string }) => LocalizedString
			/**
			 * Você deseja remover o anúncio {title}?
			 */
			announcements: (arg: { title: string }) => LocalizedString
			/**
			 * Você deseja remover o testemunho de {name}?
			 */
			testimonials: (arg: { name: string }) => LocalizedString
			/**
			 * Você deseja remover o relatório {title}?
			 */
			reports: (arg: { title: string }) => LocalizedString
			/**
			 * Você deseja remover a família ofertante representada pelo(a) {name}?
			 */
			'offeror-families': (arg: { name: string }) => LocalizedString
			/**
			 * Você deseja remover a família acolhida representada pelo(a) {name}?
			 */
			'welcomed-families': (arg: { name: string }) => LocalizedString
			/**
			 * Você deseja remover o campo missionário {designation}?
			 */
			fields: (arg: { designation: string }) => LocalizedString
			/**
			 * Você deseja remover a igreja {name}?
			 */
			churches: (arg: { name: string }) => LocalizedString
			/**
			 * Você deseja remover o colaborador {title}?
			 */
			collaborators: (arg: { title: string }) => LocalizedString
			/**
			 * Você deseja remover a oferta coletada de {month}/{year}?
			 */
			'collected-offers': (arg: { month: number, year: number }) => LocalizedString
			/**
			 * Você deseja remover o voluntário {name}?
			 */
			volunteers: (arg: { name: string }) => LocalizedString
		}
		isStatusTransform: {
			/**
			 * Sim
			 */
			'true': () => LocalizedString
			/**
			 * Não
			 */
			'false': () => LocalizedString
		}
		yup: {
			/**
			 * {field} é um campo obrigatório.
			 */
			required: (arg: { field: string }) => LocalizedString
			/**
			 * Você deve escoher um dentre os valores: {enums}.
			 */
			oneOf: (arg: { enums: string }) => LocalizedString
			/**
			 * {field} deve ter no mínimo {length} caracteres.
			 */
			min: (arg: { field: string, length: number }) => LocalizedString
			/**
			 * {field} deve ter no máximo {length} caracteres.
			 */
			max: (arg: { field: string, length: number }) => LocalizedString
			/**
			 * {field} deve ser no mínimo {value}.
			 */
			minNumber: (arg: { field: string, value: number }) => LocalizedString
			/**
			 * {field} deve ser no máximo {value}.
			 */
			maxNumber: (arg: { field: string, value: number }) => LocalizedString
			/**
			 * {field} deve ser um número válido.
			 */
			number: (arg: { field: string }) => LocalizedString
			/**
			 * {field} deve ser um número inteiro.
			 */
			integer: (arg: { field: string }) => LocalizedString
			/**
			 * {field} deve ser um e-mail válido.
			 */
			email: (arg: { field: string }) => LocalizedString
		}
		axios: {
			/**
			 * Os arquivos são muito grandes!
			 */
			fileSizeError: () => LocalizedString
			/**
			 * Servidor não está disponível
			 */
			serverNotAvailable: () => LocalizedString
		}
		inputs: {
			/**
			 * Campo Missionário
			 */
			fieldLabel: () => LocalizedString
		}
		inputFile: {
			/**
			 * Escolher Arquivo
			 */
			chooseFile: () => LocalizedString
			/**
			 * Escolher Arquivos
			 */
			chooseFiles: () => LocalizedString
		}
	}
	signup: {
		/**
		 * Criar Conta
		 */
		pageTitle: () => LocalizedString
		authModal: {
			'0': {
				/**
				 * Criar Conta
				 */
				title: () => LocalizedString
				/**
				 * Por favor, insira seu e-mail
				 */
				subTitle: () => LocalizedString
				/**
				 * Próximo
				 */
				buttonText: () => LocalizedString
			}
			'1': {
				/**
				 * Verificação
				 */
				title: () => LocalizedString
				/**
				 * Digite o seu token
				 */
				subTitle: () => LocalizedString
				/**
				 * Validar
				 */
				buttonText: () => LocalizedString
			}
			'2': {
				/**
				 * Último Passo
				 */
				title: () => LocalizedString
				/**
				 * Preencha os dados faltantes
				 */
				subTitle: () => LocalizedString
				/**
				 * Criar Conta
				 */
				buttonText: () => LocalizedString
			}
		}
		inputs: {
			/**
			 * E-mail
			 */
			emailLabel: () => LocalizedString
			/**
			 * Token
			 */
			tokenLabel: () => LocalizedString
			/**
			 * Primeiro Nome
			 */
			firstNameLabel: () => LocalizedString
			/**
			 * Último Nome
			 */
			lastNameLabel: () => LocalizedString
			/**
			 * Senha
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Repita a senha
			 */
			confirmPasswordLabel: () => LocalizedString
		}
		yupMessages: {
			/**
			 * Apenas dígitos alfanuméricos são válidos
			 */
			tokenMatch: () => LocalizedString
			/**
			 * Token inválido!
			 */
			tokenInvalid: () => LocalizedString
			/**
			 * As senhas devem ser iguais
			 */
			confirmPassword: () => LocalizedString
		}
		links: {
			/**
			 * Login
			 */
			loginText: () => LocalizedString
			/**
			 * Recuperar Conta
			 */
			forgotPasswordText: () => LocalizedString
		}
	}
	testimonials: {
		list: {
			/**
			 * Testemunhos
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Testemunhos
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Testemunho
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Testemunhos
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Testemunho
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Testemunhos
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Testemunho
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Texto
				 */
				textLabel: () => LocalizedString
			}
		}
	}
	toast: {
		/**
		 * Fechar
		 */
		closeText: () => LocalizedString
	}
	tokens: {
		list: {
			/**
			 * Tokens
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Tokens
				 */
				name: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Token
				 */
				tokenLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Usado
				 */
				usedLabel: () => LocalizedString
				/**
				 * Tipo
				 */
				typeLabel: () => LocalizedString
				/**
				 * Payload
				 */
				payloadLabel: () => LocalizedString
				/**
				 * Expiração
				 */
				expirationLabel: () => LocalizedString
			}
		}
	}
	users: {
		list: {
			/**
			 * Usuários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Usuários
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Usuário
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Acesso
				 */
				roleLabel: () => LocalizedString
				/**
				 * Último Acesso
				 */
				lastAccessLabel: () => LocalizedString
			}
			/**
			 * (não informado)
			 */
			lastNamePlaceholder: () => LocalizedString
		}
		add: {
			/**
			 * Usuários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Usuário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Acesso
				 */
				roleLabel: () => LocalizedString
				/**
				 * Último Acesso
				 */
				lastAccessLabel: () => LocalizedString
			}
			roles: {
				/**
				 * Voluntário
				 */
				volunteer: () => LocalizedString
				/**
				 * Admin
				 */
				admin: () => LocalizedString
				/**
				 * Web Master
				 */
				webMaster: () => LocalizedString
			}
			profilePic: {
				/**
				 * Imagem de Perfil
				 */
				altText: () => LocalizedString
				/**
				 * Editar
				 */
				editText: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Usuários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Usuário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Acesso
				 */
				roleLabel: () => LocalizedString
				/**
				 * Último Acesso
				 */
				lastAccessLabel: () => LocalizedString
			}
			roles: {
				/**
				 * Voluntário
				 */
				volunteer: () => LocalizedString
				/**
				 * Admin
				 */
				admin: () => LocalizedString
				/**
				 * Web Master
				 */
				webMaster: () => LocalizedString
			}
			profilePic: {
				/**
				 * Imagem de Perfil
				 */
				altText: () => LocalizedString
				/**
				 * Editar
				 */
				editText: () => LocalizedString
			}
		}
	}
	volunteers: {
		list: {
			/**
			 * Voluntários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Voluntários
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Voluntário
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Data de Admissão
				 */
				joinedDateLabel: () => LocalizedString
				/**
				 * Ocupação
				 */
				occupationLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Pastor
				 */
				priestLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Voluntários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Voluntário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Data de Admissão
				 */
				joinedDateLabel: () => LocalizedString
				/**
				 * Ocupação
				 */
				occupationLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Pastor
				 */
				priestLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
			occupations: {
				/**
				 * Presidente
				 */
				president: () => LocalizedString
				/**
				 * Vice-Presidente
				 */
				vicePresident: () => LocalizedString
				/**
				 * Coordenador Geral
				 */
				geralCoordinator: () => LocalizedString
				/**
				 * Coordenador 01
				 */
				coordinator01: () => LocalizedString
				/**
				 * Conselheiro 01
				 */
				counselor01: () => LocalizedString
				/**
				 * Conselheiro 02
				 */
				counselor02: () => LocalizedString
				/**
				 * Conselheiro 03
				 */
				counselor03: () => LocalizedString
				/**
				 * Web Master
				 */
				webMaster: () => LocalizedString
				/**
				 * Tesoureiro 01
				 */
				treasurer01: () => LocalizedString
				/**
				 * Tesoureiro 02
				 */
				treasurer02: () => LocalizedString
				/**
				 * Instrutor Acadêmico 01
				 */
				academicInstructor01: () => LocalizedString
				/**
				 * Instrutor Acadêmico 02
				 */
				academicInstructor02: () => LocalizedString
				/**
				 * Secretário(a) Executiv(o)
				 */
				executiveSecretary: () => LocalizedString
				/**
				 * Secretário(a) Auxiliar
				 */
				auxiliarySecretary: () => LocalizedString
				/**
				 * Coordenador 02
				 */
				coordinator02: () => LocalizedString
				/**
				 * Coordenador Interno
				 */
				infieldCoordinator: () => LocalizedString
				/**
				 * Coordenador Externo
				 */
				outfieldCoordinator: () => LocalizedString
				/**
				 * Coletor
				 */
				collector: () => LocalizedString
				/**
				 * Serviço de Apoio
				 */
				supportService: () => LocalizedString
			}
			profilePic: {
				/**
				 * Imagem de Perfil
				 */
				altText: () => LocalizedString
				/**
				 * Editar
				 */
				editText: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Voluntários
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Voluntário
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Nome
				 */
				nameLabel: () => LocalizedString
				/**
				 * Primeiro Nome
				 */
				firstNameLabel: () => LocalizedString
				/**
				 * Último Nome
				 */
				lastNameLabel: () => LocalizedString
				/**
				 * E-mail
				 */
				emailLabel: () => LocalizedString
				/**
				 * Data de Admissão
				 */
				joinedDateLabel: () => LocalizedString
				/**
				 * Ocupação
				 */
				occupationLabel: () => LocalizedString
				/**
				 * Igreja
				 */
				churchLabel: () => LocalizedString
				/**
				 * Pastor
				 */
				priestLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
			occupations: {
				/**
				 * Presidente
				 */
				president: () => LocalizedString
				/**
				 * Vice-Presidente
				 */
				vicePresident: () => LocalizedString
				/**
				 * Coordenador Geral
				 */
				geralCoordinator: () => LocalizedString
				/**
				 * Coordenador 01
				 */
				coordinator01: () => LocalizedString
				/**
				 * Conselheiro 01
				 */
				counselor01: () => LocalizedString
				/**
				 * Conselheiro 02
				 */
				counselor02: () => LocalizedString
				/**
				 * Conselheiro 03
				 */
				counselor03: () => LocalizedString
				/**
				 * Web Master
				 */
				webMaster: () => LocalizedString
				/**
				 * Tesoureiro 01
				 */
				treasurer01: () => LocalizedString
				/**
				 * Tesoureiro 02
				 */
				treasurer02: () => LocalizedString
				/**
				 * Instrutor Acadêmico 01
				 */
				academicInstructor01: () => LocalizedString
				/**
				 * Instrutor Acadêmico 02
				 */
				academicInstructor02: () => LocalizedString
				/**
				 * Secretário(a) Executiv(o)
				 */
				executiveSecretary: () => LocalizedString
				/**
				 * Secretário(a) Auxiliar
				 */
				auxiliarySecretary: () => LocalizedString
				/**
				 * Coordenador 02
				 */
				coordinator02: () => LocalizedString
				/**
				 * Coordenador Interno
				 */
				infieldCoordinator: () => LocalizedString
				/**
				 * Coordenador Externo
				 */
				outfieldCoordinator: () => LocalizedString
				/**
				 * Coletor
				 */
				collector: () => LocalizedString
				/**
				 * Serviço de Apoio
				 */
				supportService: () => LocalizedString
			}
			profilePic: {
				/**
				 * Imagem de Perfil
				 */
				altText: () => LocalizedString
				/**
				 * Editar
				 */
				editText: () => LocalizedString
			}
		}
	}
	'welcomed-families': {
		list: {
			/**
			 * Famílias Acolhidas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Famílias Acolhidas
				 */
				name: () => LocalizedString
				/**
				 * Adicionar Família Acolhida
				 */
				buttonText: () => LocalizedString
			}
			collectionHeader: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
		}
		add: {
			/**
			 * Famílias Acolhidas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Adicionar Família Acolhida
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
		}
		edit: {
			/**
			 * Famílias Acolhidas
			 */
			pageTitle: () => LocalizedString
			appHeader: {
				/**
				 * Editar Família Acolhida
				 */
				name: () => LocalizedString
				/**
				 * Salvar
				 */
				buttonText: () => LocalizedString
			}
			inputs: {
				/**
				 * Representante
				 */
				representativeLabel: () => LocalizedString
				/**
				 * Observação
				 */
				observationLabel: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
